# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
general:
  branches:
    only:
    - /feature-.*/
    - master
    - stable
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/cuotos/gcp-disk-snapshot
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            set -x
            if [ ${CIRCLE_BRANCH} == "master" ];then
              echo DOCKER_IMAGE=latest >> $BASH_ENV
            else
              echo DOCKER_IMAGE=${CIRCLE_BRANCH} >> $BASH_ENV
            fi
      - run: 
          command: go test -v ./...
      - run: 
          command: docker build -t cuotos/gcp-disk-snapshot:${DOCKER_IMAGE} .
      - run: 
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - deploy: 
          command: docker push cuotos/gcp-disk-snapshot:${DOCKER_IMAGE}
