name: Docker build and push
on: [push]

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cuotos/actions-test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
